[platformio]
default_envs = megaatmega2560_w5100

[env:megaatmega2560_w5100]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps =
    arduino-libraries/Ethernet @ ^2.0.2
build_flags =
    -I ../../../include
    -DRUDP_MAX_FRAME=128
    -DRUDP_MAX_QUEUE=8

